export const FETCH_USER = "FETCH_USER";
export const SIGN_OUT = "SIGN_OUT";
export const ADD_USER = "ADD_USER";
export const ADD_FAVORITE_MOVIE = "ADD_FAVORITE_MOVIE";
export const FETCH_ALL_FAVORITE_MOVIES = "FETCH_ALL_FAVORITE_MOVIES";
export const DELETE_FAVORITE_MOVIE = "DELETE_FAVORITE_MOVIE";

export const FAVORITE_MOVIES_USERS = "FAVORITE_MOVIES_USERS";


export const FAVORITE_MOVIES = "FAVORITE_MOVIES_USERS";
